name: CI

on:
  push:
    branches:
      - main  # Or your main development branch name
  pull_request:
    branches:
      - main # Or your main development branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11.10' # Specify your Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt # Assuming you have a requirements.txt file
        pip install Flask Flask-SQLAlchemy Flask-Mail Werkzeug pytest

    - name: Run tests
      run: |
        pytest # Or python -m unittest test_project2.py
