name: Run Tests
 
on:
  workflow_call:
 
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
 
      - name: Run tests
        run: echo "Running some tests..."
